// src/components/AppShell.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { Compass, Home, Plus, MessageCircle, User } from "lucide-vue-next";
import { computed } from "vue";
import { useRoute } from "vue-router";
import { api, getToken } from "@/lib/api";

const route = useRoute();
const hideChrome = computed(
  () =>
    route.path === "/onboarding" ||
    route.path === "/auth" ||
    route.path === "/register",
);

const meQuery = useQuery({
  queryKey: ["me"],
  queryFn: api.me,
  enabled: Boolean(getToken()),
  retry: false,
});

const initial = computed(() => meQuery.data.value?.firstName?.[0] ?? "A");

const topLinks = [
  { to: "/", label: "Поездки", exact: true },
  { to: "/chats", label: "Чаты", exact: false },
  { to: "/profile", label: "Профиль", exact: false },
] as const;

const bottomItems = [
  { to: "/", label: "Главная", icon: Home, exact: true },
  { to: "/create", label: "Создать", icon: Plus, exact: false },
  { to: "/chats", label: "Чаты", icon: MessageCircle, exact: false },
  { to: "/profile", label: "Профиль", icon: User, exact: false },
] as const;
</script>

<template>
  <div class="app-shell">
    <header v-if="!hideChrome" class="app-shell__header">
      <div class="app-shell__header-inner">
        <RouterLink to="/" class="app-shell__logo">
          <span class="app-shell__logo-icon">
            <Compass class="icon" />
          </span>
          <span class="app-shell__logo-text">waymate</span>
        </RouterLink>
        <nav class="app-shell__nav">
          <RouterLink
            v-for="l in topLinks"
            :key="l.to"
            :to="l.to"
            class="app-shell__nav-link"
            active-class="app-shell__nav-link--active"
            :exact-active-class="l.exact ? 'app-shell__nav-link--active' : undefined"
          >
            {{ l.label }}
          </RouterLink>
        </nav>
        <div class="app-shell__actions">
          <RouterLink to="/create" class="app-shell__create-btn">
            <Plus class="icon icon--sm" /> Создать поездку
          </RouterLink>
          <RouterLink :to="getToken() ? '/profile' : '/auth'" class="app-shell__avatar-link">
            {{ initial }}
          </RouterLink>
        </div>
      </div>
    </header>

    <main :class="['app-shell__main', { 'app-shell__main--with-nav': !hideChrome }]">
      <slot />
    </main>

    <nav v-if="!hideChrome" class="app-shell__bottom-nav">
      <ul class="app-shell__bottom-list">
        <li v-for="item in bottomItems" :key="item.to">
          <RouterLink
            :to="item.to"
            class="app-shell__bottom-link"
            active-class="app-shell__bottom-link--active"
            :exact-active-class="item.exact ? 'app-shell__bottom-link--active' : undefined"
          >
            <component :is="item.icon" class="icon" />
            <span>{{ item.label }}</span>
          </RouterLink>
        </li>
      </ul>
    </nav>
  </div>
</template>

// src/components/app-shell.tsx
import { Link, useRouterState } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Home, Plus, MessageCircle, User, Compass } from "lucide-react";
import type { ReactNode } from "react";
import { api, getToken } from "@/lib/api";

export function AppShell({ children }: { children: ReactNode }) {
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const hideChrome = pathname === "/onboarding" || pathname === "/auth" || pathname === "/register";

  return (
    <div className="min-h-screen bg-background text-foreground">
      {!hideChrome && <TopNav />}
      <main className={hideChrome ? "" : "pb-24 lg:pb-0"}>{children}</main>
      {!hideChrome && <BottomNav />}
    </div>
  );
}

function TopNav() {
  const meQuery = useQuery({
    queryKey: ["me"],
    queryFn: api.me,
    enabled: Boolean(getToken()),
    retry: false,
  });
  const initial = meQuery.data?.firstName?.[0] ?? "A";
  const links = [
    { to: "/", label: "Поездки" },
    { to: "/chats", label: "Чаты" },
    { to: "/profile", label: "Профиль" },
  ] as const;
  return (
    <header className="sticky top-0 z-30 hidden border-b border-border/60 bg-background/85 backdrop-blur lg:block">
      <div className="mx-auto flex h-16 max-w-[1300px] items-center gap-8 px-10">
        <Link to="/" className="flex items-center gap-2">
          <span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-hero text-primary-foreground">
            <Compass className="h-5 w-5" />
          </span>
          <span className="font-display text-xl font-semibold">waymate</span>
        </Link>
        <nav className="flex items-center gap-1">
          {links.map((l) => (
            <Link
              key={l.to}
              to={l.to}
              className="rounded-full px-4 py-2 text-sm font-medium text-muted-foreground transition hover:bg-secondary hover:text-foreground"
              activeProps={{ className: "bg-secondary text-foreground" }}
              activeOptions={{ exact: l.to === "/" }}
            >
              {l.label}
            </Link>
          ))}
        </nav>
        <div className="ml-auto flex items-center gap-3">
          <Link
            to="/create"
            className="inline-flex items-center gap-2 rounded-full bg-[image:var(--gradient-hero)] px-4 py-2 text-sm font-medium text-primary-foreground shadow-[var(--shadow-lift)] transition hover:opacity-95"
          >
            <Plus className="h-4 w-4" /> Создать поездку
          </Link>
          <Link to={getToken() ? "/profile" : "/auth"} className="grid h-9 w-9 place-items-center rounded-full bg-secondary text-sm font-semibold">
            {initial}
          </Link>
        </div>
      </div>
    </header>
  );
}

function BottomNav() {
  const items: Array<{ to: "/" | "/create" | "/chats" | "/profile"; label: string; icon: typeof Home; exact?: boolean }> = [
    { to: "/", label: "Главная", icon: Home, exact: true },
    { to: "/create", label: "Создать", icon: Plus },
    { to: "/chats", label: "Чаты", icon: MessageCircle },
    { to: "/profile", label: "Профиль", icon: User },
  ];
  return (
    <nav className="fixed inset-x-0 bottom-0 z-30 border-t border-border/60 bg-background/95 backdrop-blur lg:hidden">
      <ul className="mx-auto grid max-w-md grid-cols-4">
        {items.map(({ to, label, icon: Icon, exact }) => (
          <li key={to}>
            <Link
              to={to}
              activeOptions={{ exact }}
              className="flex flex-col items-center gap-1 px-2 py-3 text-[11px] text-muted-foreground transition"
              activeProps={{ className: "text-primary" }}
            >
              <Icon className="h-5 w-5" />
              <span>{label}</span>
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}
