// src/components/TripAvatar.vue
<script setup lang="ts">
import { tripAvatarColors, tripInitials } from "@/lib/format";

const props = defineProps<{
  from: string;
  to: string;
  size?: number;
}>();
</script>

<template>
  <div
    class="trip-avatar"
    :style="{
      width: `${props.size ?? 56}px`,
      height: `${props.size ?? 56}px`,
      background: `linear-gradient(135deg, ${tripAvatarColors(props.from, props.to).bg}, ${tripAvatarColors(props.from, props.to).fg})`,
      fontSize: `${(props.size ?? 56) * 0.36}px`,
    }"
  >
    {{ tripInitials(props.from, props.to) }}
  </div>
</template>

// src/components/trip-avatar.tsx
import { tripAvatarColors, tripInitials } from "@/lib/format";

export function TripAvatar({
  from, to, size = 56,
}: { from: string; to: string; size?: number }) {
  const { bg, fg } = tripAvatarColors(from, to);
  return (
    <div
      className="relative grid shrink-0 place-items-center overflow-hidden rounded-full font-display font-semibold"
      style={{ width: size, height: size, background: `linear-gradient(135deg, ${bg}, ${fg})`, color: "white", fontSize: size * 0.36 }}
    >
      {tripInitials(from, to)}
    </div>
  );
}
